import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

import Navbar from "./components/Navbar";

import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next E-Commerce 14",
  description: "Generated by Next E-Commerce 14",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-br">
        <body className={clsx(inter.className, 'bg-slate-700')}>
          <Navbar />
          <main className="bg-slate-700 h-screen p-16">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}